# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='shops')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_img', models.ImageField(upload_to='shops')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_desc', models.CharField(max_length=40)),
                ('goods_price', models.FloatField()),
                ('goods_orignal_price', models.FloatField(blank=True)),
                ('goods_img', models.ImageField(upload_to='shops')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('shop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shop_title', models.CharField(max_length=40)),
                ('shop_desc', models.CharField(max_length=40)),
                ('shop_addr', models.CharField(max_length=200)),
                ('shop_time', models.CharField(max_length=40)),
                ('shop_phone', models.CharField(max_length=40)),
                ('shop_latitude', models.FloatField()),
                ('shop_longitude', models.FloatField()),
                ('shop_icon', models.ImageField(upload_to='shops')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='shop_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.ShopInfo'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='shop_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.ShopInfo'),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='goods_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.GoodsInfo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='shop_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.ShopInfo'),
        ),
    ]
