# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0002_auto_20180131_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_img', models.ImageField(upload_to='shops')),
                ('shop_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.ShopInfo')),
            ],
        ),
    ]
