# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop2', '0003_shopdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop2.ShopInfo')),
            ],
        ),
    ]
